### ISSUE TITLE
Unknown extension .css & unknown mode bug when importing <RichText /> exactly as in Website template

### ISSUE THREAD

**Issue by whatisloves** [payloadcms/payload#11017]
### Describe the Bug

`"Lexical => JSX converter: Blocks converter: found banner block, but no converter is provided"` and `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css"` when importing <RichText> component and doing exactly as in the Payload website template. 

Find link to public github repo with this bug reproduced below

### Link to the code that reproduces this issue

https://github.com/whatisloves/help-me-with-lexical.git

### Reproduction Steps

What to do to reproduce the issue:

1. npx create-next-app@latest  
2. then follow the instructions in "https://payloadcms.com/docs/getting-started/installation" "Adding to existing app"

As part of step 2. I copy-pasted the entire (payload) folder from https://github.com/payloadcms/payload/tree/main/templates/blank/src/app/(payload) and separated my front-end into (front-end)

3. apart from following all the payload instructions, I found it necessary to follow my own steps to make the automatic type generation work
3.1 I added the following to package.json:
    `"generate:types": "cross-env NODE_OPTIONS=--no-deprecation payload generate:types",`
    `"payload": "cross-env NODE_OPTIONS=--no-deprecation payload"`
3.2 I did "npm i cross-env"
3.3 I added the following lines to "payload.config.ts"
    ```
    const filename = fileURLToPath(import.meta.url)
    const dirname = path.dirname(filename)

    typescript: {
        outputFile: path.resolve(dirname, 'payload-types.ts'),
    },
   ```
Only then running "pnpm run payload generate:types" created a "payload-types.ts" with the following console message:
    ```
    [12:01:51] INFO: Compiling TS types for Collections and Globals...
    [12:01:51] INFO: Types written to /Users/whatisloves/help-me-app/payload-types.ts
    ```

4. I copy-pasted the code for Banner block from Payload Website template. After pasting config, I generated types. Then inserted banner component.
5. In admin panel I put some random text in RTE and made a banner component. Upon rendering I am getting this message in the console:
    `"Lexical => JSX converter: Blocks converter: found banner block, but no converter is provided"`

    and "unknown" mode shows on the webpage where <RichText /> component should render

6. When I try to run "npm run payload generate:types" I am getting the following error:
    ```
    node:internal/process/promises:394
        triggerUncaughtException(err, true /* fromPromise */);
      TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for /Users/whatisloves/help-me-app/node_modules/@payloadcms/richtext-lexical/dist/exports/react/components/RichText/index.css
          at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:183:9)
          at defaultGetFormat (node:internal/modules/esm/get_format:209:36)
          at defaultLoad (node:internal/modules/esm/load:119:22)
          at async nextLoad (node:internal/modules/esm/hooks:748:22)
          at async load (file:///Users/whatisloves/help-me-app/node_modules/tsx/dist/esm/index.mjs?1738856302886:2:1762)
          at async nextLoad (node:internal/modules/esm/hooks:748:22)
          at async Hooks.load (node:internal/modules/esm/hooks:385:20)
          at async handleMessage (node:internal/modules/esm/worker:199:18) {
        code: 'ERR_UNKNOWN_FILE_EXTENSION'
      }
```

### Which area(s) are affected? (Select all that apply)

plugin: richtext-lexical

### Environment Info

```text
Binaries:
  Node: 23.7.0
  npm: 10.9.2
  Yarn: 1.22.22
  pnpm: 9.4.0
Relevant Packages:
  payload: 3.20.0
  next: 15.1.6
  @payloadcms/db-mongodb: 3.20.0
  @payloadcms/graphql: 3.20.0
  @payloadcms/next/utilities: 3.20.0
  @payloadcms/richtext-lexical: 3.20.0
  @payloadcms/translations: 3.20.0
  @payloadcms/ui/shared: 3.20.0
  react: 19.0.0
  react-dom: 19.0.0
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.2.0: Fri Dec  6 18:40:14 PST 2024; root:xnu-11215.61.5~2/RELEASE_ARM64_T8103
  Available memory (MB): 8192
  Available CPU cores: 8
```

**Comment by akhrarovsaid** [comment]
Hey @whatisloves,

I believe this was fixed in 3.21.0 thanks to [this PR](https://github.com/payloadcms/payload/pull/10997)! Go ahead and update your payload versions and it should work for you just fine.

**Comment by whatisloves** [comment]
@akhrarovsaid Thanks a lot, updated both my projects and type generation doesn't break. However, I am still getting an error `[ Server ] Lexical => JSX converter: Blocks converter: found banner block, but no converter is provided` for when I try to render the <RichText />. I intelligently copy-pasted the code from Website template, so I guess it should render the Banner block correctly?

**Comment by AlessioGr** [comment]
@whatisloves closing this, as the CSS issue has been fixed in the latest release.

As for 

> [ Server ] Lexical => JSX converter: Blocks converter: found banner block, but no converter is provided

in your page.tsx you are importing the default RichText component from `import { RichText } from "@payloadcms/richtext-lexical/react";`. You're not using your own RichText component where you're passing the custom converters
