### ISSUE TITLE
Block field with array causes error when copying data from one locale to another

### ISSUE THREAD

**Issue by Citingdude** [payloadcms/payload#11924]
### Describe the Bug

ERROR: There was an error copying data from "en" to "fr"

```
ERROR: There was an error copying data from "en" to "fr"
    err: {
      "type": "ValidationError",
      "message": "error:followingFieldsInvalid id",
      "stack":
          ValidationError: error:followingFieldsInvalid id
              at upsertRow (webpack-internal:///(rsc)/./packages/drizzle/src/upsertRow/index.ts:367:19)
              at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
              at async Object.updateOne (webpack-internal:///(rsc)/./packages/drizzle/src/updateOne.ts:57:20)
              at async updateDocument (webpack-internal:///(rsc)/./packages/payload/src/collections/operations/utilities/update.ts:211:18)
              at async updateByIDOperation (webpack-internal:///(rsc)/./packages/payload/src/collections/operations/updateByID.ts:118:22)
              at async copyDataFromLocale (webpack-internal:///(rsc)/./packages/ui/src/utilities/copyDataFromLocale.ts:207:10)
              at async copyDataFromLocaleHandler (webpack-internal:///(rsc)/./packages/ui/src/utilities/copyDataFromLocale.ts:129:16)
              at async /Users/glenn/workspace/wisemen/payload/payload-reproduction/node_modules/.pnpm/next@15.2.3_@opentelemetry+api@1.9.0_@playwright+test@1.50.0_babel-plugin-macros@3.1.0_babel-_d64hrgp6dzrr74jbhxuvaexsxm/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:438:2357
              at async handleAction (/Users/glenn/workspace/wisemen/payload/payload-reproduction/node_modules/.pnpm/next@15.2.3_@opentelemetry+api@1.9.0_@playwright+test@1.50.0_babel-plugin-macros@3.1.0_babel-_d64hrgp6dzrr74jbhxuvaexsxm/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:437:23434)
              at async renderToHTMLOrFlightImpl (/Users/glenn/workspace/wisemen/payload/payload-reproduction/node_modules/.pnpm/next@15.2.3_@opentelemetry+api@1.9.0_@playwright+test@1.50.0_babel-plugin-macros@3.1.0_babel-_d64hrgp6dzrr74jbhxuvaexsxm/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:443:26714)
              at async doRender (/Users/glenn/workspace/wisemen/payload/payload-reproduction/node_modules/.pnpm/next@15.2.3_@opentelemetry+api@1.9.0_@playwright+test@1.50.0_babel-plugin-macros@3.1.0_babel-_d64hrgp6dzrr74jbhxuvaexsxm/node_modules/next/dist/server/base-server.js:1650:34)
              at async DevServer.renderToResponseWithComponentsImpl (/Users/glenn/workspace/wisemen/payload/payload-reproduction/node_modules/.pnpm/next@15.2.3_@opentelemetry+api@1.9.0_@playwright+test@1.50.0_babel-plugin-macros@3.1.0_babel-_d64hrgp6dzrr74jbhxuvaexsxm/node_modules/next/dist/server/base-server.js:1915:28)
              at async DevServer.renderPageComponent (/Users/glenn/workspace/wisemen/payload/payload-reproduction/node_modules/.pnpm/next@15.2.3_@opentelemetry+api@1.9.0_@playwright+test@1.50.0_babel-plugin-macros@3.1.0_babel-_d64hrgp6dzrr74jbhxuvaexsxm/node_modules/next/dist/server/base-server.js:2393:24)
              at async DevServer.renderToResponseImpl (/Users/glenn/workspace/wisemen/payload/payload-reproduction/node_modules/.pnpm/next@15.2.3_@opentelemetry+api@1.9.0_@playwright+test@1.50.0_babel-plugin-macros@3.1.0_babel-_d64hrgp6dzrr74jbhxuvaexsxm/node_modules/next/dist/server/base-server.js:2430:32)
              at async DevServer.pipeImpl (/Users/glenn/workspace/wisemen/payload/payload-reproduction/node_modules/.pnpm/next@15.2.3_@opentelemetry+api@1.9.0_@playwright+test@1.50.0_babel-plugin-macros@3.1.0_babel-_d64hrgp6dzrr74jbhxuvaexsxm/node_modules/next/dist/server/base-server.js:1003:25)
              at async NextNodeServer.handleCatchallRenderRequest (/Users/glenn/workspace/wisemen/payload/payload-reproduction/node_modules/.pnpm/next@15.2.3_@opentelemetry+api@1.9.0_@playwright+test@1.50.0_babel-plugin-macros@3.1.0_babel-_d64hrgp6dzrr74jbhxuvaexsxm/node_modules/next/dist/server/next-server.js:304:17)
              at async DevServer.handleRequestImpl (/Users/glenn/workspace/wisemen/payload/payload-reproduction/node_modules/.pnpm/next@15.2.3_@opentelemetry+api@1.9.0_@playwright+test@1.50.0_babel-plugin-macros@3.1.0_babel-_d64hrgp6dzrr74jbhxuvaexsxm/node_modules/next/dist/server/base-server.js:895:17)
              at async /Users/glenn/workspace/wisemen/payload/payload-reproduction/node_modules/.pnpm/next@15.2.3_@opentelemetry+api@1.9.0_@playwright+test@1.50.0_babel-plugin-macros@3.1.0_babel-_d64hrgp6dzrr74jbhxuvaexsxm/node_modules/next/dist/server/dev/next-dev-server.js:371:20
              at async Span.traceAsyncFn (/Users/glenn/workspace/wisemen/payload/payload-reproduction/node_modules/.pnpm/next@15.2.3_@opentelemetry+api@1.9.0_@playwright+test@1.50.0_babel-plugin-macros@3.1.0_babel-_d64hrgp6dzrr74jbhxuvaexsxm/node_modules/next/dist/trace/trace.js:157:20)
              at async DevServer.handleRequest (/Users/glenn/workspace/wisemen/payload/payload-reproduction/node_modules/.pnpm/next@15.2.3_@opentelemetry+api@1.9.0_@playwright+test@1.50.0_babel-plugin-macros@3.1.0_babel-_d64hrgp6dzrr74jbhxuvaexsxm/node_modules/next/dist/server/dev/next-dev-server.js:368:24)
              at async invokeRender (/Users/glenn/workspace/wisemen/payload/payload-reproduction/node_modules/.pnpm/next@15.2.3_@opentelemetry+api@1.9.0_@playwright+test@1.50.0_babel-plugin-macros@3.1.0_babel-_d64hrgp6dzrr74jbhxuvaexsxm/node_modules/next/dist/server/lib/router-server.js:247:21)
              at async handleRequest (/Users/glenn/workspace/wisemen/payload/payload-reproduction/node_modules/.pnpm/next@15.2.3_@opentelemetry+api@1.9.0_@playwright+test@1.50.0_babel-plugin-macros@3.1.0_babel-_d64hrgp6dzrr74jbhxuvaexsxm/node_modules/next/dist/server/lib/router-server.js:438:24)
              at async NextCustomServer.requestHandlerImpl (/Users/glenn/workspace/wisemen/payload/payload-reproduction/node_modules/.pnpm/next@15.2.3_@opentelemetry+api@1.9.0_@playwright+test@1.50.0_babel-plugin-macros@3.1.0_babel-_d64hrgp6dzrr74jbhxuvaexsxm/node_modules/next/dist/server/lib/router-server.js:462:13)
              at async Server.<anonymous> (file:///Users/glenn/workspace/wisemen/payload/payload-reproduction/test/dev.ts:1:2848)
      "name": "ValidationError",
      "status": 400,
      "data": {
        "id": "c33f859e-0602-4da0-8844-88903918490a",
        "errors": [
          {
            "message": "error:valueMustBeUnique",
            "path": "id"
          }
        ]
      },
      "isPublic": false,
      "isOperational": true
    }
```

### Link to the code that reproduces this issue

https://github.com/Citingdude/payload-reproduction

### Reproduction Steps

1. Fill in test.env with your postgres url
2. Run Payload
3. Create a new Post for 'EN' locale
4. Add a TextColumn block in "Blocks"
5. Fill in a title and add a "Column"
6. Fill in the "Column"
7. "Copy to locale" => from 'en' to 'fr'
8. Click "Copy" button
9. Validation error shows in console

### Which area(s) are affected? (Select all that apply)

db-postgres, Not sure, area: core

### Environment Info

```text
Binaries:
  Node: 22.13.1
  npm: 11.0.0
  Yarn: N/A
  pnpm: 9.15.0
Relevant Packages:
  payload: 3.27.0
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:22 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6041
  Available memory (MB): 24576
  Available CPU cores: 12
```

**Comment by Bjornnyborg** [comment]
@Citingdude i think this will be solved by this PR i made: https://github.com/payloadcms/payload/pull/11887 😊

**Comment by mikkelwf** [comment]
This issue is not solved

**Comment by Bjornnyborg** [comment]
This issue was resolved, but seems like it got re-introduced recently. ☹️

**Comment by hesselberg** [comment]
Still an issue, would be good to get some traction on this. Anyone working with locales and postgres are screwed on this functionality

**Comment by nunomalta** [comment]
Any workaround or solution for this?

**Comment by Bjornnyborg** [comment]
@nunomalta Yes, i have one - but it's really annoying. 😅

1. Use the "Copy field" on the block field itself, instead of the "Copy to locale"
2. Change locale and paste the blocks on the block field, the page will now fail if you try to save, because of the duplicate id's
3. Duplicate all blocks, and delete the original ones - seems like duplicating actually handles the id's correctly

This is not the 1-click action it should have been, but if you have advanced blocks, it may still be faster than building the blocks from scratch. 😊

**Comment by mahmutisci** [comment]
I'm experiencing this problem too, and there are other issues when copying block field areas. It's an incredibly problematic issue; you have to add each piece of content individually to localize it, which is a very bad experience.

**Comment by JessRynkar** [comment]
Hi! Apologies for the long delay in getting a response here, is anyone still experiencing this on the latest version `v3.74.0`? I know a couple fixes went around regarding `copy to locale`, it may potentially have resolved this issue.

**Comment by JessRynkar** [comment]
Since we haven’t heard back in a while and this issue relates to several releases ago, we’re going to close it for now. 

That said, if you’re still seeing this behavior on the latest version (v3.77.0), please let me know and we can re-open this!
