### ISSUE TITLE
Stale data on backward/forward navigation

### ISSUE THREAD

**Issue by Janisvb** [payloadcms/payload#13390]
### Describe the Bug

1. When opening a collection item from the items list, changing a field, and pressing the back button of the browser, the value in the list shows the old value
2. When changing a field, navigating to another page and pressing the back button of the browser, the field shows the old value

![Image](https://github.com/user-attachments/assets/6b58b847-66fd-489f-8c8b-5a9cbd0b6a0c)

While the first case is only annoying, the second case can easily lead to data loss by overwriting your updates with stale data.

### Link to the code that reproduces this issue

https://github.com/janisvb/payload-reproduction

### Reproduction Steps

pnpm dev _community

1.  Navigate to http://localhost:3000/admin/collections/posts
2. Open "example post"
3. Change _example post_ to _new post_ and save
4. Press back button of browser. List still shows _example post_ as title
5. Press forward button of browser. Title field shows _example post_ instead of _new post_

### Which area(s) are affected? (Select all that apply)

area: ui

### Environment Info

```text
payload: 3.50.0
next: 15.4.4
react: 19.1.0
```

**Comment by JessRynkar** [comment]
Hi! Apologies for the long delay in getting a response here, I am unable to reproduce this behavior and it's possible it was fixed in a release since this was opened. Are you still experiencing this on the latest version `v3.75.0`?

**Comment by Janisvb** [comment]
No, I believe that has been fixed in a recent release.

**Comment by inetstd** [comment]
Hi, I started experience this also - I'm on 3.70.0

**Comment by inetstd** [comment]
I've updated to 3.76.0 and still have this issue.

I'll try to investigate it more
