### ISSUE TITLE
Out of date references to babel

### ISSUE THREAD

**Issue by charkour** [payloadcms/payload#1952]
# Documentation Issue

The [docs incorrectly reference babel as the transpiler](https://payloadcms.com/docs/configuration/overview#developing-within-the-config) in `overview.mdx`. I believe swc is now the compiler/transpiler: https://github.com/payloadcms/payload/pull/1779

Is there a similar way to do so with swc with what we previously did with Babel?

Thanks for the awesome work!

I checked that there we no other open issues related to babel. Thanks

**Comment by jmikrut** [comment]
Hey @charkour — we are about to release a new minor version that leverages TypeScript to transpile. I will update the docs accordingly when that version releases, but for now, I will keep this open.

Thanks for identifying this discrepancy!

**Comment by charkour** [comment]
Great! I'll look forward to that. Thanks

**Comment by jmikrut** [comment]
Hey @charkour — this is now fixed. Docs updated, new version released! Thank you for the report!

**Comment by charkour** [comment]
Great, thanks!

**Comment by charkour** [comment]
@jmikrut, how frequently does the marketing/docs site get redeployed? Still seeing the [old Babel documentation](https://payloadcms.com/docs/configuration/overview) on this page. Thank you.
