### ISSUE TITLE
Virtual field not getting populated in GraphQL query

### ISSUE THREAD

**Issue by hdodov** [payloadcms/payload#3024]
### Link to reproduction

https://github.com/hdodov/payload/tree/bug-virtual-field-hook-graphql

### To Reproduce

1. Clone the reproduction repo
2. Run `yarn test:int _community`
3. You'll see one failing test

### Describe the Bug

I have an async virtual field, as described in [the docs about virtual fields](https://payloadcms.com/blog/learn-how-virtual-fields-can-help-solve-common-cms-challenges). My setup:

- Posts collection with a category
- Categories collection with a subcategories field
- Subcategories field is a relationship field pointing to other categories

The goal is to add a virtual `parentCategory` field to the `posts` collection that is automatically populated based on the `category` field. Here's how the hook looks like:

https://github.com/hdodov/payload/blob/3fb00baaaa9876369cc3e8a954f604c5d96d2bcb/test/_community/collections/Posts/index.ts#L23-L45

When I request it over REST, it gets populated as usual:

```json
{
	"id": "64b9122a31e96e2cd569980a",
	"text": "example post",
	"category": {
		"id": "64b9122a31e96e2cd5699804",
		"title": "Child Category",
		"createdAt": "2023-07-20T10:53:30.233Z",
		"updatedAt": "2023-07-20T10:53:30.233Z"
	},
	"createdAt": "2023-07-20T10:53:30.255Z",
	"updatedAt": "2023-07-20T10:53:30.255Z",
	"parentCategory": {
		"id": "64b9122a31e96e2cd5699806",
		"title": "Parent Category",
		"subcategories": ["64b9122a31e96e2cd5699804"],
		"createdAt": "2023-07-20T10:53:30.239Z",
		"updatedAt": "2023-07-20T10:53:30.239Z"
	}
}
```

But when I make the following GraphQL query:

```gql
{
  Post(id: "${postId}") {
    parentCategory {
      id
      title
    }
  }
}
```

…I get the following result:

```json
{
	"data": {
		"Post": {
			"parentCategory": null
		}
	}
}
```

As you can see, `parentCategory` is `null`.

### Payload Version

1.11.3

**Comment by AlessioGr** [comment]
Hi @hdodov 

You're returning the whole document in your relationship field's `afterRead` - however, you have to make sure to only return the ID. Changing the return to `return parent.docs?.[0]`.id;` should fix it.

Does that help?

**Comment by hdodov** [comment]
@AlessioGr yep. That does work indeed. Thank you!

**Comment by hdodov** [comment]
@AlessioGr one strange thing, though, is that if my GraphQL query does **not** select the virtual field, the hook still gets fired (and a database query is being made). In other words, if I query this:

```gql
{
  Post(id: "${postId}") {
    text
  }
}
```

…the hook for `parentCategory` and the necessary database queries for it get fired. That seems pretty inefficient. Is this how it's supposed to work? If not, I could open a separate issue.
