### ISSUE TITLE
Array is throwing error when deleting and adding new element

### ISSUE THREAD

**Issue by MarvinVrdoljak** [payloadcms/payload#3069]
### Link to reproduction

https://demo.payloadcms.com/admin/collections/pages/64bf810192ceff2fa92abd35

### To Reproduce

- Login to your demo website
- Go to "Pages" and click on a page
- Click on "Page Layout" tab and delete an element in the layour-array
- Add a new element to the array

https://github.com/payloadcms/payload/assets/25500828/91e2b77e-2179-419b-b516-0b9d262a0100

### Describe the Bug

Array is throwing error when deleting and adding new element:
`Uncaught TypeError: Cannot read properties of undefined (reading 'reduce')`

### Payload Version

1.11.3

**Comment by JarrodMFlesch** [comment]
Hey @MarvinVrdoljak this was fixed with [this commit](https://github.com/payloadcms/payload/commit/08377cc5a7ea9d02350177e2e1d69390ee97af78), please update to `v1.11.5` to receive the fix!

I have updated the demo also 👍

**Comment by MarvinVrdoljak** [comment]
Hey @JarrodMFlesch! Unfortunately it's not fixed. :(

https://github.com/payloadcms/payload/assets/25500828/cbe8da90-779f-4f4b-bffb-4fcfc9ced076

We really like Payload and appreciate what you guys are doing - we really do! But it would be nice if you could test your system a little better before you are releasing it. We started to use Payload now for bigger clients and we are depending on a working system. We know it is quite new and it doesn't have to be perfect yet - it just has to be stable. <3

**Comment by DanRibbens** [comment]
> But it would be nice if you could test your system a little better before you are releasing it. 

I really feel this comment! We are adding e2e tests to the array field UI that will catch regressions like this.

**Comment by JarrodMFlesch** [comment]
Added tests in this [PR](https://github.com/payloadcms/payload/pull/3086/commits/e4b0c19464b831e0ab8b3caf79dcc3b5dbace055) 👍
