### ISSUE TITLE
Webpack export 'default' (imported as 'payload') was not found

### ISSUE THREAD

**Issue by hdodov** [payloadcms/payload#3494]
### Link to reproduction

https://github.com/hdodov/payload/tree/bug-webpack-warning

### To Reproduce

1. Simply import Payload in a collection, like this:

```ts
import payload from "payload";
```

https://github.com/hdodov/payload/blob/f7ef2d5e9b5af267ead2b73d05bbd708534865b8/src/collections/Posts.ts#L1

2. Run the project with `yarn dev`
3. You'll see a warning

### Describe the Bug

When using Payload 2 with the Webpack bundler, you receive the following warning once you import Payload in a collection:

```
WARNING in ./src/collections/Posts.ts 2:12-19
export 'default' (imported as 'payload') was not found in 'payload' (possible exports: __esModule, webpackBundler)
```

### Payload Version

2.0.0

**Comment by hdodov** [comment]
This can be fixed by switching the ES6 import for a `require`:

```ts
const payload = require("payload");
```

…but that's not really desirable.

**Comment by jmikrut** [comment]
Hey @hdodov — I think I got to the bottom of this. We are about to publish a new version of the Webpack bundler which should resolve this issue. Will you keep an eye out for the new version and test accordingly?

**Comment by taismassaro** [comment]
hey @jmikrut, I'm still getting this error after updating to `payload` 2.0.7 and `@payloadcms/bundler-webpack` 1.0.3 when trying to use the local API in the `beforeChange` hook of a custom field to populate the value with an incremental ID based on the last item of the collection.

```ts
import payload from "payload";
import { Config } from "payload/generated-types";
import { FieldHook } from "payload/types";

export function incrementId(fieldName: string): FieldHook {
  return async ({ operation, req }) => {
    if (operation === "create") {
      const collection = req.collection.config
        .slug as keyof Config["collections"];

      const lastDoc = await payload.find({
        collection,
        sort: `-${fieldName}`,
        limit: 1,
      });

      const lastId = (lastDoc.docs[0]?.[fieldName] as number | undefined) || 0; // Default to 0 if no previous document

      const incrementedId = lastId + 1;

      return incrementedId;
    }
  };
}
```

<img width="834" alt="image" src="https://github.com/payloadcms/payload/assets/16339834/83ca3953-dbdd-454e-85d6-d376ee704820">

there's no change in functionality, just the warning in the terminal and in the console.
any suggestions of what might be the issue?

**Comment by eustachi0** [comment]
> hey @jmikrut, I'm still getting this error after updating to `payload` 2.0.7 and `@payloadcms/bundler-webpack` 1.0.3 when trying to use the local API in the `beforeChange` hook of a custom field to populate the value with an incremental ID based on the last item of the collection.
> 
> ```ts
> import payload from "payload";
> import { Config } from "payload/generated-types";
> import { FieldHook } from "payload/types";
> 
> export function incrementId(fieldName: string): FieldHook {
>   return async ({ operation, req }) => {
>     if (operation === "create") {
>       const collection = req.collection.config
>         .slug as keyof Config["collections"];
> 
>       const lastDoc = await payload.find({
>         collection,
>         sort: `-${fieldName}`,
>         limit: 1,
>       });
> 
>       const lastId = (lastDoc.docs[0]?.[fieldName] as number | undefined) || 0; // Default to 0 if no previous document
> 
>       const incrementedId = lastId + 1;
> 
>       return incrementedId;
>     }
>   };
> }
> ```
> 
> <img alt="image" width="834" src="https://user-images.githubusercontent.com/16339834/275447707-83ca3953-dbdd-454e-85d6-d376ee704820.png">
> there's no change in functionality, just the warning in the terminal and in the console. any suggestions of what might be the issue?

Me too. Same versions, same errors

**Comment by denolfe** [comment]
Re-opening because of additional reports in the thread https://discord.com/channels/967097582721572934/1160944315502170122

**Comment by mvdve** [comment]
Same issue here with payload 2.0.10 and webpack bundler 1.0.3

**Comment by hdodov** [comment]
I can confirm that the issue is resolved in:

- `payload@2.0.11`
- `@payloadcms/bundler-webpack@1.0.4`

Thank you! 🙌
