### ISSUE TITLE
Graphql returning `null` for fields of type `upload`

### ISSUE THREAD

**Issue by pzpsofficial** [payloadcms/payload#6221]
### Link to reproduction

https://github.com/pzpsofficial/payload-graphql-issue

### Describe the Bug

Hi! 

All of a sudden graphql has stopped returning any data for all media relation fields of type upload. If the field is not required I'm getting just null, and when it's I'm getting error: cannot return null for non-nullable field. 

The REST API is working as expected. The graphql just stopped working at some point.

Here is my default `media` collection with right `read` access:

```ts
import { CollectionConfig } from 'payload/types'

const Media: CollectionConfig = {
  slug: 'media',
  upload: true,
  fields: [],
  access: {
    read: () => true
  }
}

export default Media;
```

And example field that is returning `null`:
```ts
...
{
  name: 'image',
  type: 'upload',
  relationTo: 'media',
  admin: {
    condition: (_, data) => data.type === 'image',
  }
},
...
```

### To Reproduce

The thing is it just stopped working. Only thing I can think of would be that I've prepared demo about Payload at work, so I created other Payload project in the same parent directory, but it seems so impossible that I almost feel ashamed thinking about this. 

Update: I've just uploaded the reproduction repo. In order to reproduce it you need to enter admin panel, create example Page, then go to `localhost:3000/api/graphql-playground` and execute the following query. You will see `null` instead of image id in the gql response. 

```gql
query Test {
  Pages {
      docs {
        image {
          id
        }
      }
   }
}
```

### Payload Version

2.0.0

**Comment by flamedmg** [comment]
i have the same issue, it was working just fine on firay, but on saturday it stopped to work. No changes were made.

**Comment by slavanossar** [comment]
Also experiencing this issue, works in `2.14.2` but breaks after upgrading to `2.15.0`.

Possible related to #6141.

**Comment by jonowu** [comment]
I was experiencing the same issue and was able to work around it for now.

I believe this issue is caused by the `2.15.0` release. After reverting back to `2.14.0` my upload fields don't return  `null` anymore.

Likely you didn't update any packages on your side manually, but as this is a minor patch you'll want to remove the caret in your package version e.g. `^2.0.0` can be `2.0.0`

**Comment by sburgpit** [comment]
Also experiencing same issue, when upgrading from `2.14.2` to `2.15.0`

**Comment by slongiaru-dmind** [comment]
Here too update from 2.12.1 to 2.15.0.
Via the REST API it seems to work fine.

**Comment by JarrodMFlesch** [comment]
Hey everyone, thanks for the report. The fix will go out after [this PR](https://github.com/payloadcms/payload/pull/6233) is merged into main. Will also make PR for beta branch too.

**Comment by JarrodMFlesch** [comment]
Fix was released in [2.16.0](https://github.com/payloadcms/payload/releases/tag/v2.16.0).

**Comment by pzpsofficial** [comment]
@JarrodMFlesch Thanks for that fix and for all great work 💪

**Comment by ayarse** [comment]
@JarrodMFlesch I'm still having this issue on `2.16.1`.
In my case, the issue is even stranger because the upload field doesn't return `null` for every GraphQL request.

When I spam the server with requests in Altair and I can see `null` being returned for like 1/10 requests. Can this be an unresolved promise or something?

**Comment by eweren** [comment]
Having the same as @ayarse for the beta branch. Seems to only occur on media relations,

**Comment by andrewshvv** [comment]
Yes, beta branch doesn't have this fix yet.

main:
https://github.com/payloadcms/payload/commits/main/test/collections-graphql/config.ts

beta:
https://github.com/payloadcms/payload/commits/beta/test/collections-graphql/config.ts

beta doesn't have
`fix: graphql upload relations returning null`
