### ISSUE TITLE
Confirm Password Field is Ignored

### ISSUE THREAD

**Issue by tobiasiv** [payloadcms/payload#7554]
### Payload Version

3.0.0-beta.74

### Node Version

v20.9.0

### Next.js Version

15.0.0-canary.77

### Describe the Bug

This [issue](https://github.com/payloadcms/payload/issues/7461) is still possible in 3.0.0-beta.74.

### Reproduction Steps

1. Clone the [payload 3.0 demo](https://github.com/payloadcms/payload-3.0-demo)
2. Update payload to latest beta version: 3.0.0-beta.74
3. Run pnpm dev
4. Create a new user by filling in only the email and new password fields
5. Save the document
6. No error message appears when the confirm password field is left empty

**Comment by JarrodMFlesch** [comment]
Fixed yesterday with [this PR](https://github.com/payloadcms/payload/pull/7535), will be in next beta release.

**Comment by tobiasiv** [comment]
Hey @JarrodMFlesch, unfortunately, this issue still exists in beta 76, which includes the mentioned PR.

You can successfully save a user with only the email and new password fields filled in. I've also noticed another strange behaviour: when you fill out the password fields and then edit another field (e.g. email), the passwords get discarded.
