### ISSUE TITLE
Component not found in importMap - 3.0.0-beta.80

### ISSUE THREAD

**Issue by digitaledge-git** [payloadcms/payload#7677]
### Link to reproduction

https://github.com/digitaledge-git/payload3_80_issue

### Payload Version

3.0.0-beta.80

### Node Version

v20.9.0

### Next.js Version

15.0.0-canary.104

### Describe the Bug

I followed the migration guide and made all the changes. No data is being added to importMap.js. Regardless of whether it's in dev mode or production, the importMap remains empty.

Running `pnpm payload generate:importmap` fails with this error:
`> cross-env NODE_OPTIONS=--no-deprecation payload "generate:importmap"

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\d\WebstormProjects\myproject\node_modules\next\cache' imported from C:\Users\stefa\WebstormProjects\mednet-ecrep\src\payload\globals\Navigation.ts
Did you mean to import next/cache.js?
`

I suspect the error occurs because `import { revalidateTag } from 'next/cache'` is being imported to Navigation.ts

### Reproduction Steps

Add `import { revalidateTag } from 'next/cache'` to some collection or global and may add it to some hook.
Then start with dev or create a build. Lots of errors like this ones below should appear:

`getCreateMappedComponent: Component not found in importMap { identifier: 'incomingField.admin.components.Field', key: undefined }
getComponent: Component not found in importMap {
  identifier: 'incomingField.admin.components.Field',
  key: '@payloadcms/plugin-seo/client#MetaTitleComponent',
  payloadComponent: {
    clientProps: { hasGenerateTitleFn: true },
    path: '@payloadcms/plugin-seo/client#MetaTitleComponent'
  }
}
`

### Adapters and Plugins

db-mongodb

**Comment by AlessioGr** [comment]
Fixed by https://github.com/payloadcms/payload/pull/7681

**Comment by matart15** [comment]
@AlessioGr 

still happening on `3.0.0-beta.82` ( which looks tagged 1 day after merge )

![Screenshot 2024-08-16 at 5 36 53](https://github.com/user-attachments/assets/131eab48-5dc2-46b9-a922-0a9145798d52)

![Screenshot 2024-08-16 at 5 37 35](https://github.com/user-attachments/assets/d6d50c76-de09-4360-b150-e6a283b97363)

```log
❯ npx create-payload-app@beta
Need to install the following packages:
create-payload-app@3.0.0-beta.82
Ok to proceed? (y)


┌   create-payload-app
│
◇   ────────────────────────────────────────────╮
│                                               │
│  Welcome to Payload. Let's create a project!  │
│                                               │
├───────────────────────────────────────────────╯
│
◇  Project name?
│  payload-test
│
◇  Choose project template
│  website
│
◇  Select a database
│  PostgreSQL (beta)
│
◇  Enter PostgreSQL connection string
│  postgres://postgres:password@127.0.0.1:5432/payload-test
│
│
◇  Using pnpm.
│
◇  Successfully installed Payload and dependencies
│
◇  Payload project successfully created!
│
◇   Next Steps  ─────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                    │
│                                                                                                                    │
│  Launch Application:                                                                                               │
│                                                                                                                    │
│    - cd ./payload-test                                                                                             │
│    - pnpm dev or follow directions in README.md: file:///Users/matar/workplace/github/temp/payload-test/README.md  │
│                                                                                                                    │
│  Documentation:                                                                                                    │
│                                                                                                                    │
│    - Getting Started: https://payloadcms.com/docs/getting-started/what-is-payload                                  │
│    - Configuration: https://payloadcms.com/docs/configuration/overview                                             │
│                                                                                                                    │
│                                                                                                                    │
│                                                                                                                    │
├────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
│
└   Have feedback?  Visit us on GitHub: https://github.com/payloadcms/payload.

npx create-payload-app@beta  16.33s user 57.49s system 114% cpu 1:04.37 total

❯ pnpm payload                                                          Py base 05:35:02

> payload-test@1.0.0 payload /Users/matar/workplace/github/temp/payload-test
> payload


node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/matar/workplace/github/temp/payload-test/node_modules/next/cache' impo
rted from /Users/matar/workplace/github/temp/payload-test/src/payload/hooks/revalidateRedirects.ts
Did you mean to import "next/cache.js"?
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:933:10)
    at defaultResolve (node:internal/modules/esm/resolve:1157:11)
    at nextResolve (node:internal/modules/esm/hooks:866:28)
    at resolve (file:///Users/matar/workplace/github/temp/payload-test/node_modules/.pnpm/@swc-node+register@1.10.9_@swc+core@1
.7.11_@swc+types@0.1.12_typescript@5.5.4/node_modules/@swc-node/register/esm/esm.mjs:175:27)
    at async nextResolve (node:internal/modules/esm/hooks:866:22)
    at async Hooks.resolve (node:internal/modules/esm/hooks:304:24)
    at async handleMessage (node:internal/modules/esm/worker:196:18) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/matar/workplace/github/temp/payload-test/node_modules/next/cache'
}

Node.js v20.12.2
 ELIFECYCLE  Command failed with exit code 1.

```


my env info
```sh
> npx envinfo --system

  System:
    OS: macOS 14.6.1
    CPU: (12) x64 Apple M2 Max
    Memory: 7.98 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh

```

**Comment by matart15** [comment]
I had to manually replace all `3.0.0-beta.79` with `3.0.0-beta.82` inside my @package.json`

**Comment by ars3nicum** [comment]
I have same error in beta.82:
```
digest: "3095742589"
  13 |     const { exportName, path } = parsePayloadComponent(payloadComponent);
  14 |     const key = path + '#' + exportName;
> 15 |     const Component = importMap[key];
     | ^
  16 |     if (!Component && !silent) {
  17 |         console.error(`getComponent: Component not found in importMap`, {
  18 |             identifier,
 GET /admin 500 in 62ms
```

**Comment by ParkerCai** [comment]
I was getting a similar error. I tried manually change the beta version to .82 and ran the `yarn generate:importmap` after upgrade and the error went away.

**Comment by ars3nicum** [comment]
Tried it, but not working for me.

**Comment by maclong9** [comment]
I get a message saying the script `generate:importmap` doesn't exist.

**Comment by singhks0054** [comment]
**Getting the same importMap error**

![image](https://github.com/user-attachments/assets/2b96fe20-1970-4d5c-8178-558f25b979bd)

I am using these versions of the respective packages.

next- 15.0.0-canary.121
payload- 3.0.0-beta.86
