### ISSUE TITLE
Error related to pagination limit when join field is set.

### ISSUE THREAD

**Issue by energee** [payloadcms/payload#8707]
### Environment Info

Node: 22.9.0
  npm: 10.8.3
  Yarn: 1.22.22
  pnpm: 9.10.0
Relevant Packages:
  payload: 3.0.0-beta.113
  next: 15.0.0-canary.173
  @payloadcms/db-mongodb: 3.0.0-beta.113
  @payloadcms/graphql: 3.0.0-beta.113
  @payloadcms/next/utilities: 3.0.0-beta.113
  @payloadcms/richtext-lexical: 3.0.0-beta.113
  @payloadcms/translations: 3.0.0-beta.113
  @payloadcms/ui/shared: 3.0.0-beta.113
  react: 19.0.0-rc-3edc000d-20240926
  react-dom: 19.0.0-rc-3edc000d-20240926

### Describe the Bug

`Error: invalid argument to $limit stage: Expected a number in: $limit: "10"`

Once pagination is set on the collection view, the page fails due to this error.

The limit and other arguments do not get set on the URL.

When i manually set a limit argument on the url eg "?limit=100", it prevents this error.

I don't think this error was present in beta 111.

### Reproduction Steps

This occurs when there is a join field on the collection view being displayed.

Use the "per page" pagination, which subsequently should set the limit argument on the URL.

### Adapters and Plugins

db-mongodb

**Comment by energee** [comment]
This appears to be resolved in 114

**Comment by energee** [comment]
Sorry, spoke too soon still seeing the issue.

![Image](https://github.com/user-attachments/assets/024174e9-fb8c-4525-ac86-e199ab52db2d)

**Comment by JarrodMFlesch** [comment]
@energee I am trying to follow but struggling to. Can you provide a screenshot of the view you are experiencing this in?

**Comment by energee** [comment]
It seems like i can adjust the pagination but when i navigate to: /admin/collection/<collection-slug> and payload retrieves the limit from mongoDB, it fails (looks like its getting a string?)

**Comment by BrianJM** [comment]
I am also getting this error. It appears related to `join` field, as noted previously. For example: `Collection_A` with a `join` field to `Collection_B` that has a `relationship` field back to `Collection_A` will show this error.

`"@payloadcms/db-mongodb": "3.0.0-beta.118",`

```
 ⨯ node_modules/.pnpm/mongodb@4.17.1_@aws-sdk+client-sso-oidc@3.675.0_@aws-sdk+client-sts@3.670.0_/node_modules/mongodb/lib/cmap/connection.js (231:1) @ Connection.onMessage
 ⨯ MongoServerError: invalid argument to $limit stage: Expected a number in: $limit: "10"
    at MessageStream.emit (node:events:519:28)
    at Socket.emit (node:events:519:28)
digest: "2508765017"
  229 |                 }
  230 |                 if (document.ok === 0 || document.$err || document.errmsg || document.code) {
> 231 |                     callback(new error_1.MongoServerError(document));
      | ^
  232 |                     return;
  233 |                 }
  234 |             }
```
> ![Image](https://github.com/user-attachments/assets/986a704a-d7af-43e4-b12e-6ea31daa6d66)

**Comment by andershermansen** [comment]
Try to update to [v3.0.0-beta.121](https://github.com/payloadcms/payload/releases/tag/v3.0.0-beta.121) or later where #8913 is fixed. The error message seems the same.

**Comment by energee** [comment]
From what I can see so far, it appears to be resolved, running beta.123

**Comment by HriBB** [comment]
I'm still seeing thig even in v3.0.0-beta.124. 
```
Error: invalid argument to $limit stage: Expected a number in: $limit: "100"
    at resolveErrorDev (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0_babel-plugin-react-compiler@0.0.0-experimental-48eb8f4-20240822_react-dom@19.0.0-_olzgyrhn3cj6yjvy663zgvkzo4/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js:1790:63)
    at processFullStringRow (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0_babel-plugin-react-compiler@0.0.0-experimental-48eb8f4-20240822_react-dom@19.0.0-_olzgyrhn3cj6yjvy663zgvkzo4/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js:2067:17)
    at processFullBinaryRow (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0_babel-plugin-react-compiler@0.0.0-experimental-48eb8f4-20240822_react-dom@19.0.0-_olzgyrhn3cj6yjvy663zgvkzo4/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js:2055:7)
    at progress (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0_babel-plugin-react-compiler@0.0.0-experimental-48eb8f4-20240822_react-dom@19.0.0-_olzgyrhn3cj6yjvy663zgvkzo4/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js:2258:17)
```

It works on one collection, but does not work on the other.

**Comment by energee** [comment]
@HriBB you might want to try clearing out your payload-preferences table, it looks like the config is being sanitized on its way INTO the database so it won't go away until that is reset.

**Comment by HriBB** [comment]
Thanks @energee! That solved the problem ;)
